# version: '3'

services:
  web:
    build: .

    # command: python manage.py runserver 0.0.0.0:3000  # テンプレートの設定
    # command: bash

    ports:
      # - "3000:3000"  # テンプレートの設定(ruby?)
      - '8000:8000'

    volumes:
      - '.:/django_tutorial'
    depends_on:
      - db
    
    # チュートリアル中のみ有効、その後はコメントアウト
    tty: true
    stdin_open: true

  
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      # - "5433:5432"  # このポート番号の設定について質問する
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django_develop
      - POSTGRES_PASSWORD=postgres

    # チュートリアル中はコメントアウト
    # healthcheck:
    #   test: "psql -U postgres"
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

volumes:
  db-data: